services:
  - type: web
    name: cospharm-pricing-engine
    env: node
    region: oregon
    plan: free
    buildCommand: pnpm install && pnpm db:push && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
