import { randomUUID } from "crypto";

export const seedProducts = [
  {
    id: randomUUID(),
    name: "ABHAYRAB VACCINE",
    barcode: "8906117650065",
    basePrice: "1400.00",
    productDiscount: "5",
    bonusPattern: "",
    category: "Vaccines",
    active: "yes" as const,
  },
  {
    id: randomUUID(),
    name: "Cipromed 500",
    barcode: "6003412790235",
    basePrice: "85.00",
    productDiscount: "15",
    bonusPattern: "1@40%",
    category: "Antibiotics",
    active: "yes" as const,
  },
  {
    id: randomUUID(),
    name: "Clindamycin 150mg",
    barcode: "6008758001083",
    basePrice: "120.00",
    productDiscount: "10",
    bonusPattern: "1@30%",
    category: "Antibiotics",
    active: "yes" as const,
  },
  {
    id: randomUUID(),
    name: "CP-Azithromycin 500mg",
    barcode: "8906117650065",
    basePrice: "95.00",
    productDiscount: "12",
    bonusPattern: "1@50%",
    category: "Antibiotics",
    active: "yes" as const,
  },
  {
    id: randomUUID(),
    name: "Doxicap 100mg",
    barcode: "6008758002165",
    basePrice: "65.00",
    productDiscount: "8",
    bonusPattern: "1@20%",
    category: "Antibiotics",
    active: "yes" as const,
  },
];

export const seedCustomers = [
  {
    id: randomUUID(),
    name: "ABC Pharmacy",
    email: "contact@abcpharmacy.na",
    phone: "+264 61 123 4567",
    logFeeDiscount: "14",
    customerType: "wholesaler",
    active: "yes" as const,
  },
  {
    id: randomUUID(),
    name: "HealthPlus Distributors",
    email: "info@healthplus.na",
    phone: "+264 61 234 5678",
    logFeeDiscount: "18",
    customerType: "wholesaler",
    active: "yes" as const,
  },
  {
    id: randomUUID(),
    name: "MediCare Retail",
    email: "sales@medicare.na",
    phone: "+264 61 345 6789",
    logFeeDiscount: "5",
    customerType: "retail",
    active: "yes" as const,
  },
  {
    id: randomUUID(),
    name: "Wellness Pharmacy",
    email: "info@wellness.na",
    phone: "+264 61 456 7890",
    logFeeDiscount: "10",
    customerType: "retail",
    active: "yes" as const,
  },
];
